name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Pack NuGet
        run: dotnet pack -c Release -p:PackageVersion=${{ github.ref_name }} -o ./artifacts/nupkgs --nologo

      - name: Push NuGet
        run: dotnet nuget push './artifacts/nupkgs/*.nupkg' -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
